enum MyEnum
{
	A, // a comment
	B, // another comment
	C  // last comment
}

enum MyOtherEnum : (int val)
{
	A { 1 }, // a comment
	B { 2 }, // another comment
	C { 3 }, // last comment
}

enum MyThirdEnum : (int val)
{
	A { 1 }, // a comment
	B { 2 }, // another comment
	C { 3 }  // last comment
}

fn void main()
{
	// if (foo) {
	//     bar();
	// }

	int a   = 1; // comment 1
	// in between
	int bbb = 2; // comment 2
}
